[package]
name = "pesc"
version = "0.1.0"
authors = ["Kiëd Llaentenn <kiedtl@tilde.team>"]
edition = "2018"

[dependencies]
terminal_size = "0.1.13"
serde = "1.0"
getopts = "0.2"
rustyline-derive = "0.3.1"

[dependencies.rustyline]
version = "6.3"
default-features = false
