[package]
name = "pesc"
version = "0.1.0"
authors = ["Kiëd Llaentenn <kiedtl@tilde.team>"]
edition = "2018"

[dependencies]
rustyline-derive = "0.3.1"

[dependencies.rustyline]
version = "6.3"
default-features = false
