[package]
name = "pescli"
version = "0.1.0"
authors = ["Kiëd Llaentenn <kiedtl@tilde.team>"]
edition = "2018"

[dependencies]
terminal_size = "0.1"
getopts = "0.2"
rustyline-derive = "0.3"

[dependencies.pesc]
path = "../pesc-lib"

[dependencies.rustyline]
version = "6.3"
default-features = false
